name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          # full history for correct version tag
          fetch-depth: 0

      - name: Set macOS deployment target
        if: ${{ matrix.os == 'macos-latest' }}
        run: echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | cut -d '.' -f 1-2)" >> $GITHUB_ENV

      # used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3

      - name: Install dependencies on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install hdf5 numpy

      - name: Build wheels on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # install required libraries
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y blas-devel lapack-devel &&
            yum install -y epel-release &&
            yum install -y hdf5-devel
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD: "{cp38,cp39,cp310,cp311,cp312}-manylinux_{x86_64,aarch64}"
          # disable building PyPy wheels
          CIBW_SKIP: pp*
          CIBW_MANYLINUX_X86_64_IMAGE:  manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28

      - name: Build wheels on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD: "{cp310,cp311,cp312}-macosx_arm64"
          # disable building PyPy wheels
          CIBW_SKIP: pp*

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
